export enum EnvVariables {
  // Application Configuration
  NODE_ENV = 'NODE_ENV',
  NEST_PORT = 'NEST_PORT',

  // JWT Configuration
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  // CORS Configuration
  FRONTEND_URL = 'FRONTEND_URL',

  // Database Configuration
  DATABASE_URL = 'DATABASE_URL',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_CA_FILE = 'DATABASE_CA_FILE',

  // Redis Configuration
  REDIS_URL = 'REDIS_URL',
  REDIS_TLS_CERT = 'REDIS_TLS_CERT',

  // Email verification configuration
  AUTH_EMAIL_TOKEN_TTL = 'AUTH_EMAIL_TOKEN_TTL',
  AUTH_REQUIRE_EMAIL_CONFIRMATION = 'AUTH_REQUIRE_EMAIL_CONFIRMATION',

  // Google OAuth Configuration
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_IOS_CLIENT_ID = 'GOOGLE_IOS_CLIENT_ID',
  GOOGLE_ANDROID_CLIENT_ID = 'GOOGLE_ANDROID_CLIENT_ID',

  // Apple OAuth Configuration
  APPLE_CLIENT_ID = 'APPLE_CLIENT_ID',
  APPLE_TEAM_ID = 'APPLE_TEAM_ID',
  APPLE_KEY_ID = 'APPLE_KEY_ID',
  APPLE_PRIVATE_KEY = 'APPLE_PRIVATE_KEY',
}
