/**
 * Factory Pattern Example E2E Test
 *
 * This test demonstrates using Testcontainers + Factories
 * for easy, isolated test data generation.
 *
 * Run with: yarn test:e2e --testPathPattern=factories-example
 */

import { UserFactory, LibraryItemFactory, HighlightFactory, LabelFactory } from './factories'
import { getTestDataSource } from './setup/test-datasource'
import { UserRole } from '../src/user/enums/user-role.enum'
import { StatusType } from '../src/user/entities/user.entity'

describe('Factory Pattern Example (e2e)', () => {
  it('should create test data using factories', async () => {
    // Verify testcontainer datasource is available
    const dataSource = getTestDataSource()
    expect(dataSource.isInitialized).toBe(true)

    // Create a user
    const user = await UserFactory.create({
      email: 'factory-test@example.com',
      name: 'Factory Test User',
    })

    expect(user.id).toBeDefined()
    expect(user.email).toBe('factory-test@example.com')
    expect(user.password).toBeDefined() // bcrypt hash

    // Create a library item for this user
    const item = await LibraryItemFactory.create({
      userId: user.id,
      title: 'Amazing Article About Testing',
    })

    expect(item.id).toBeDefined()
    expect(item.userId).toBe(user.id)
    expect(item.title).toBe('Amazing Article About Testing')
    expect(item.slug).toBeDefined() // Slug is auto-generated by factory

    // Create highlights for the article
    const highlight1 = await HighlightFactory.withColor(item.id, user.id, 'yellow')
    const highlight2 = await HighlightFactory.withColor(item.id, user.id, 'red')

    expect(highlight1.color).toBe('yellow')
    expect(highlight2.color).toBe('red')
    expect(highlight1.quote).toBeDefined() // Faker-generated

    // Create labels
    const labels = await LabelFactory.createManyForUser(user.id, 3)

    expect(labels).toHaveLength(3)
    expect(labels[0].name).toBeDefined()
    expect(labels[0].color).toMatch(/^#[0-9A-F]{6}$/i) // Hex color

    console.log('✅ Successfully created test data with factories!')
    console.log('  - User:', user.email)
    console.log('  - Library Item:', item.title)
    console.log('  - Highlights:', 2)
    console.log('  - Labels:', labels.length)
  })

  it('should build entities in memory (for unit tests)', () => {
    // Build without saving to database (for mocking)
    const user = UserFactory.build({
      email: 'mock@example.com',
      role: UserRole.ADMIN,
    })

    expect(user.email).toBe('mock@example.com')
    expect(user.role).toBe(UserRole.ADMIN)
    // No database call was made

    const item = LibraryItemFactory.buildArchived(user.id)
    expect(item.folder).toBe('archive')
    expect(item.state).toBe('ARCHIVED')
    // No database call was made
  })

  it('should use factory helper methods', async () => {
    const user = await UserFactory.create()

    // Helper methods for common scenarios
    const adminUser = await UserFactory.admin()
    expect(adminUser.role).toBe(UserRole.ADMIN)

    const pendingUser = await UserFactory.pending()
    expect(pendingUser.status).toBe(StatusType.PENDING)

    const archivedItem = await LibraryItemFactory.archived(user.id)
    expect(archivedItem.folder).toBe('archive')

    const itemWithProgress = await LibraryItemFactory.withProgress(user.id, 75)
    expect(itemWithProgress.readingProgressTopPercent).toBe(75)

    console.log('✅ Factory helper methods work perfectly!')
  })
})
