import Foundation

public enum LocalText {
  static func localText(key: String, comment: String? = nil) -> String {
    NSLocalizedString(key, bundle: .module, comment: comment ?? "no comment provided by developer")
  }

  static let signInScreenHeadline = localText(key: "signInScreenHeadline")
  static let googleAuthButton = localText(key: "googleAuthButton")
  static let registrationViewSignInHeadline = localText(key: "registrationViewSignInHeadline")
  static let registrationViewSignUpHeadline = localText(key: "registrationViewSignUpHeadline")
  public static let registrationViewHeadline = localText(key: "registrationViewHeadline")
  public static let networkError = localText(key: "error.network")
  public static let genericError = localText(key: "error.generic")
  static let invalidCredsLoginError = localText(key: "loginError.invalidCreds")
  public static let saveArticleSavedState = localText(key: "saveArticleSavedState")
  public static let saveArticleProcessingState = localText(key: "saveArticleProcessingState")
  public static let extensionAppUnauthorized = localText(key: "extensionAppUnauthorized")
  static let dismissButton = localText(key: "dismissButton")
  static let usernameValidationErrorInvalid = localText(key: "username.validation.error.invalidPattern")
  static let usernameValidationErrorTooShort = localText(key: "username.validation.error.tooshort")
  static let usernameValidationErrorTooLong = localText(key: "username.validation.error.toolong")
  
  static let labelsGeneric = localText(key: "labels.generic")
  static let emailsGeneric = localText(key: "emails.generic")
  static let subscriptionsGeneric = localText(key: "subscriptions.generic")
  static let textToSpeechGeneric = localText(key: "textToSpeech.generic")
  static let privacyPolicyGeneric = localText(key: "privacy.policy.generic")
  static let termsAndConditionsGeneric = localText(key: "termsAndConditions.generic")
  static let feedbackGeneric = localText(key: "feedback.generic")
  static let manageAccountGeneric = localText(key: "manageAccount.generic")
  static let logoutGeneric = localText(key: "logout.generic")
  static let doneGeneric = localText(key: "done.generic")
  static let cancelGeneric = localText(key: "cancel.generic")
  static let inboxGeneric = localText(key: "inbox.generic")
  static let readLaterGeneric = localText(key: "readLater.generic")
  static let newslettersGeneric = localText(key: "newsletters.generic")
  static let allGeneric = localText(key: "all.generic")
  static let archivedGeneric = localText(key: "archived.generic")
  static let highlightedGeneric = localText(key: "highlighted.generic")
  static let filesGeneric = localText(key: "files.generic")
  static let newestGeneric = localText(key: "newest.generic")
  static let oldestGeneric = localText(key: "oldest.generic")
  static let recentlyReadGeneric = localText(key: "recentlyRead.generic")
  static let recentlyPublishedGeneric = localText(key: "recentlyPublished.generic")
  static let createLabelMessage = localText(key: "create.label.message")
  static let createNewEmailMessage = localText(key: "create.new.email.message")
  static let newslettersDescription = localText(key: "newsletters.description")
  static let labelsPurposeDescription = localText(key: "labels.purpose.description")
  static let noCurrentSubscriptionsMessage = localText(key: "no.current.subscriptions.message")
}
